// src/main/java/com/example/server/user/dto/UserRegistrationDto.java
package com.example.server.user.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

// You might also add Jakarta validation annotations here for registration specific rules
// import jakarta.validation.constraints.NotBlank;
// import jakarta.validation.constraints.Email;
// import jakarta.validation.constraints.Size;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserRegistrationDto {
    // ID is usually not provided during registration, it's generated by the system
    private String firstName;
    private String lastName;
    private String username;
    private String email;
    private String password; // <-- Password is required for registration
    private String gender;
    private String phone;
    private String image;
    private String role; // Defaulted in User entity, might not be needed in registration DTO if always
                         // 'USER'
}